version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_ORIGIN=http://localhost:8080
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests